### ISSUE TITLE
Philio PST02-1C sensor door/temp/light to homey athom

### ISSUE THREAD

**Issue by kennybeu** [Inversion-NL/com.philio#13]
What is your Homey version (Settings → System)?

1.1.2

Hey i should love to lets the pst02-1c sensors works on the homey.
https://github.com/athombv/homey/issues/1281

![pst02-1c](https://cloud.githubusercontent.com/assets/25205719/22075997/864e31e4-ddae-11e6-863c-efd87dc1f816.jpg)

**Comment by Inversion-NL** [comment]
Added via https://github.com/Inversion-NL/com.philio/pull/11
