### ISSUE TITLE
PST sensor - please add parameter to disable window/door

### ISSUE THREAD

**Issue by djanssen1** [Inversion-NL/com.philio#19]
Hi there,

I'm using the sensor without window/door sensor. It is possible to disable this with a config in parameter 5. Unfortunately this option is not available in drop down. For most users drop down is best so can you add this feature or make it possible to enter the value same as with PSM type sensors

**Comment by Inversion-NL** [comment]
Could you create a pull request for this, please?

**Comment by djanssen1** [comment]
Created pull request

**Comment by Inversion-NL** [comment]
https://github.com/Inversion-NL/com.philio/pulls
It's not there or am I missing something?

**Comment by djanssen1** [comment]
I'm not a developer so that's why I added it here as a change/feature request
