### ISSUE TITLE
Inclusion of PST02-A not working

### ISSUE THREAD

**Issue by robertraaijmakers** [Inversion-NL/com.philio#2]
Tried to include the PST02-A. The device gets included in Homey but none of the events are handled. Only seems to have the temperature.

I have created a branch #1 where I tried (tried, did not succeed 👎 ) to fix the device.. played with some settings and changed some parameters. The branch has some tooltip fixes, extra parameter support etc.

The PST02-A seems to become a 'brick' after adding it to Homey. When I remove the contact it doesn't light up the led, also motion is not recognised with a blink of the led... (the led (not the status reports) do work when the device is put in "testing" mode by the dip switch on the back).

Hopefully you can see what the issue is and fix it. Otherwise I'll have to dive further into it on another evening next week.

**Comment by Inversion-NL** [comment]
I don't have that specific device so I'm unable to help you there, sorry.
