### ISSUE TITLE
Include PAN 16-1

### ISSUE THREAD

**Issue by stefanwitkamp** [Inversion-NL/com.philio#27]
Hi, would it be possible to include PAN16-1 based on the information from the Z-Wave Alliance and the implementation of PAN11 (which has the same functionality)? Information (including product ID):
https://products.z-wavealliance.org/products/2001

**Comment by Inversion-NL** [comment]
Yes but I really don't have time to troubleshoot the issue if it isn't working in one go, sorry.

**Comment by stefanwitkamp** [comment]
I see. Maybe we can try and sideload the new version to verify if it works with a know partner that has Homey + the plug?

Settings:

![pan16](https://user-images.githubusercontent.com/4272462/31668547-ccfe6922-b352-11e7-9c98-b099aa736da9.png)

**Comment by stefanwitkamp** [comment]
Ps, I understand this is a 'try in one go'. Let's see where we get.

**Comment by jolny** [comment]
@Inversion-NL I've made a pull request for the PAN16-1, can you accept it and we'll see it it works? Thanks!
I was unable to test it this week unfortunately.

**Comment by Inversion-NL** [comment]
I'm also unable to test since I don't have the device.
I'll await your test before merging your PR then.

**Comment by jolny** [comment]
Hi again!
I've made another commit now, we've tested the plug and it works now :)
It needs a new icon (using PAN11 svg files at the moment), but other than
that everything seems OK.
So please accept the PR :D

2017-10-26 11:44 GMT+02:00 Inversion-NL <notifications@github.com>:

**Comment by Inversion-NL** [comment]
Great, thanks
