### ISSUE TITLE
No Battery-Level-Report PST02-A

### ISSUE THREAD

**Issue by CyberSponk** [Inversion-NL/com.philio#37]
No Battery-Level-Report PST02-A > See here because didn't know if this is an Issue of Homey itself or this App: https://github.com/athombv/homey/issues/2131

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC11.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC11.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC13.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.8-EXP from 08.03.18.

**Comment by Inversion-NL** [comment]
I don't have this device so I won't be able to troubleshoot this.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.11-EXP.

**Comment by CyberSponk** [comment]
Changed all Philio to Fibaro > Could not assist here in future. Closed this Ticket.
