### ISSUE TITLE
Please add PAN03 In wall single relay (1 way) switch module

### ISSUE THREAD

**Issue by klim123123** [Inversion-NL/com.philio#66]
Please add PAN03 In wall single relay (1 way) switch module
with energy metter

https://rus.z-wave.me/drive/?file=e9fcc888e7f893a52584109a8612dd2adf45

**Comment by JohanBendz** [comment]
Hi @klim123123, please add the device as a generic Z-wave device and get back with this information:

Device model/name:
Manufacture ID:
Product Type ID:
Product ID:

**Comment by klim123123** [comment]
Device model/name: In Wall Signle relay PAN03-1 (Switch-A)
Manufacture ID: 316
Product Type ID: 1
Product ID: 15

**Comment by JohanBendz** [comment]
Added to Test version 0.1.3, please try and give feedback

**Comment by klim123123** [comment]
It's works on/off and power metter. Thank you!

**Comment by JohanBendz** [comment]
Thanks for the positive feedback @klim123123 ! Happy to help :)
