### ISSUE TITLE
Philio temp/humidity sensor

### ISSUE THREAD

**Issue by margin1234** [Inversion-NL/com.philio#70]
Hi I’ve got the temp/humidity sensor. The temp registers but not the humidity
Can you help pls

Thx
K

**Comment by JohanBendz** [comment]
Hi @margin1234 , is this still an issue?

**Comment by margin1234** [comment]
Hi, I haven’t used it since I last emailed
Has it been fixed and should I try again?

**Comment by JohanBendz** [comment]
Hi again @margin1234, I'v done a few updates so it could work. Can you please post your device data so I can check:
		manufacturerId: 
		productTypeId: 
		productId:

**Comment by margin1234** [comment]
Seems to be working now.
Thanks for your help
K


[image: IMG_0145.PNG]
[image: IMG_0146.PNG]
Kevin Chu
