### ISSUE TITLE
Philio App for Siren PH-PSE02-1B can't play DoorChime

### ISSUE THREAD

**Issue by HakanDicander** [Inversion-NL/com.philio#79]
When creating a Flow to play the DoorChime sound on the Philio Siren an error flowcard_not_registered appears in Homey. The App should send a NOTIFICATION_REPORT command to the siren. Please see the attached PDF for details.
[PhiloSirenProblem.pdf](https://github.com/JohanBendz/com.philio/files/6379766/PhiloSirenProblem.pdf)

**Comment by ReneVerwoerd** [comment]
I just bought the Philio PSE02 and want to use is as a DoorChime as well. 
@JohanBendz is it possible for you to fix the "flowcard_not_registered" error?
@HakanDicander Did you by any chance found a workaround to get the other sounds to work?

![image](https://user-images.githubusercontent.com/122882798/212896744-d2b15089-3989-4477-aa85-b859eb8290ef.png)

**Comment by JohanBendz** [comment]
Hi @ReneVerwoerd.
Ooops. looks like I made some typos.. a new test version is on it's way but it is also a test version for the new Homey Pro - using SDK 3 and an updated Z-wave driver... so I really really need feedback on how it works... 
https://homey.app/a/com.philio/test/

**Comment by ReneVerwoerd** [comment]
Thank you so much for updating! I will test it tomorrow, the kids a sleeping right now, not a good time to test a siren, haha! :-)

**Comment by HakanDicander** [comment]
Hi, wonderful that there is some action regarding this!
In my understanding the only way to make the PSE02 to play different sounds is to send a notification command to the siren device, so please check if that is being done in the App. The slightest error or doing something else will result in no sound or in the default loud aram sound. I attach my original PDF that have info about how to do it.
I did find a way to work-around the problem, so in case it helps anyone of you, I share the Flow I start when I want my PSE02-1B play the dorr-bell sound.



Sorry for the Swedish, that is how my Homey show things, but I think you can understand.
There is a Z-Wave App, it has a Send card where you specify the bytes that will be sent as a Zwave-command to a given node id (see below). If you check at the end of the attached PDF you can see what values to you should put instead of the 0x06 and 0x16 to make it sound in other ways.
I use the Card from the Philio app to turn the siren off after 3 seconds, it works fine.
The node id to put in the Zwave Send card you find on the advanced settings for your Philio Device, here is how it looks in my Homey, I marked the node id with a red ring.


 If anyone of you have any more question about this I am happy to answer, I will however go skiing the rest of the week, so I can't try anything out until the earliest next week.
Best Regards
Håkan Dicander    On Monday, January 30, 2023 at 09:18:36 PM GMT+1, ReneVerwoerd ***@***.***> wrote:  
 
 


Thank you so much for updating! I will test it tomorrow, the kids a sleeping right now, not a good time to test a siren, haha! :-)

**Comment by ReneVerwoerd** [comment]
> Hi @ReneVerwoerd.
> Ooops. looks like I made some typos.. a new test version is on it's way but it is also a test version for the new Homey Pro - using SDK 3 and an updated Z-wave driver... so I really really need feedback on how it works...
> https://homey.app/a/com.philio/test/

Hi @JohanBendz, 

it still needs some TLC:
1. Install Siren works fine
2. Turning it on by ‘on/off’ button in app doesn’t work (“cloud not get device by id”)
3. Add flow card doesn’t work (keeps loading)

![53A7DAE3-72A7-4AE4-AC28-5BDFC5EF1B0D](https://user-images.githubusercontent.com/122882798/215780890-34edc0b2-3474-4607-81eb-868ad8444473.png)
![CF34F334-142A-4363-9835-FD3A6236A788](https://user-images.githubusercontent.com/122882798/215780907-eed3b58c-a221-430f-9451-d39a3b2c65fa.png)

**Comment by JohanBendz** [comment]
Hi again.
Please send a crash report form the app, mark it with your name/alias.

**Comment by ReneVerwoerd** [comment]
I’ve made a diagnostic report and is says to give you this code: 754510ec-1a52-457a-80ad-7959dedb7e42
Is that what you need? Sorry, never made a crash report before

**Comment by JohanBendz** [comment]
Thanks @ReneVerwoerd, you did great! :)

New version published, please try and let me know what happens. Send new diag report if you run into problems.

**Comment by ReneVerwoerd** [comment]
@JohanBendz here you go:
1f74deab-7fd6-40a3-bf85-46cfffba7f56

![86195B5F-564E-4FA0-B979-31544465A1CE](https://user-images.githubusercontent.com/122882798/216070612-0d6d8408-5423-4a05-9257-771861848fba.jpeg)
![69B5B890-31AF-4258-983E-76C1230BEE45](https://user-images.githubusercontent.com/122882798/216070615-6da6b6be-ab00-4c17-8ab3-e0e1d7548085.jpeg)

**Comment by JohanBendz** [comment]
Thx a bunch @ReneVerwoerd, new version out.

**Comment by ReneVerwoerd** [comment]
@JohanBendz here you go:
e0c5cef5-3c6b-4d0f-ac09-74634ff0f9ff
![3FAB8A1A-F70D-49A5-95C6-03FD349678C6](https://user-images.githubusercontent.com/122882798/216078880-03dab562-73c3-493a-b5ac-8ec573031ed2.png)

**Comment by JohanBendz** [comment]
@ReneVerwoerd
hahaha, closing in.. It's a pain in the **** not to have the devices one develop support for.. well well.. one more test version released.

**Comment by ReneVerwoerd** [comment]
@JohanBendz 
For me it’s absolutely no problem to help with this fix! Just grateful that you spend time and effort to do this! 🙏

Next diagnosic report: abdafe15-eea3-40fe-8e99-d03f35bfc6b1
![14F992CF-0681-419C-B880-F57DEE6706E3](https://user-images.githubusercontent.com/122882798/216259705-843223de-3d7c-43a2-a859-14f62bd4f569.png)

**Comment by JohanBendz** [comment]
@ReneVerwoerd 
Thanks, I really appreciate your help!
New test version published.

**Comment by ReneVerwoerd** [comment]
@JohanBendz 
Diag report: 9f577c29-9485-4ece-a416-d8b6af428df2

![460B6401-7A81-4D61-A9BC-B94504109F04](https://user-images.githubusercontent.com/122882798/216313366-758de3a5-d49c-4127-86c1-bc9074f2a0e6.png)

**Comment by JohanBendz** [comment]
@ReneVerwoerd, oh.. darn.. typo... fixed! :)

**Comment by ReneVerwoerd** [comment]
@JohanBendz next one: 
😉
5656f1a5-15fa-4f79-81f2-3d59e6d7d675
![Uploading 839F8100-B98C-47D5-8D49-C2380127927D.png…]()

**Comment by ReneVerwoerd** [comment]
@JohanBendz next one:
5656f1a5-15fa-4f79-81f2-3d59e6d7d675
![EE3B2CFE-0471-4C1F-8F8B-7B31767D8DAD](https://user-images.githubusercontent.com/122882798/216317537-218745b4-d8a7-4db4-be20-433354288239.png)

**Comment by JohanBendz** [comment]
@ReneVerwoerd
Oh.. no comment... lol... new version out..

**Comment by ReneVerwoerd** [comment]
@JohanBendz The app works!! I can use diffrent chimes!
thank you very much for your effort! Much appriciated!

**Comment by JohanBendz** [comment]
@ReneVerwoerd, great news 😊👍
Then I'll fix rest of the drivers just like this one.
Thanks you for enduring the massive testing 😂
