### ISSUE TITLE
App support for Homey Beta

### ISSUE THREAD

**Issue by CederholmA** [Inversion-NL/com.philio#83]
Would like support for Homey Beta through the Homey Bridge.

**Comment by macdelft** [comment]
+1, i would love to see this support as well!
@JohanBendz can you confirm if this is worked on?

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.philio/issues/88

**Comment by Dici71** [comment]
Hi,

we use several Philios PAN08 who don't work after update the actual SDK3 beta.

please see the attached picture.....



![PHOTO-2023-01-31-19-08-44](https://user-images.githubusercontent.com/90046346/215847555-ae947eba-ac6c-44a0-86c6-ecc99611ccce.jpg)
