### ISSUE TITLE
Update for Homey Pro 2023 coming?

### ISSUE THREAD

**Issue by Karpazu** [Inversion-NL/com.philio#89]
Hi,

Can you please update your app to be compatible with Homey Pro 2023.

Thanks, Karpazu

**Comment by JohanBendz** [comment]
Hi @Karpazu.
Yes, I will update all apps  I manage to SDK3. This will make them support Homey Pro 2023.
I can't promise this app will ever support the bridge though as Athom have to approve pushing an app to the cloud.

**Comment by Karpazu** [comment]
Hi!

Good to hear 👍

Thanks

**Comment by Dici71** [comment]
Hi,

seems that first homeys will be shipped by mid of January...have you got a actual status on the Philio App Update ?

**Comment by ReneVerwoerd** [comment]
> Hi @Karpazu. Yes, I will update all apps I manage to SDK3. This will make them support Homey Pro 2023. I can't promise this app will ever support the bridge though as Athom have to approve pushing an app to the cloud.

@JohanBendz When you update the app to SDK3, could you please also fix this: https://github.com/JohanBendz/com.philio/issues/79#issuecomment-1385338391

Many thanks in advance! :-)

**Comment by JohanBendz** [comment]
See https://github.com/JohanBendz/com.philio/issues/91
