### ISSUE TITLE
Please update for homey pro 2023.

### ISSUE THREAD

**Issue by ghost** [Inversion-NL/com.philio#91]

**Comment by ReneVerwoerd** [comment]
+1

And please fix this issue so we can use all chimes. :-D
(https://github.com/JohanBendz/com.philio/issues/79#issuecomment-1385338391)

**Comment by JohanBendz** [comment]
A new test version is out, using SDK 3 and a new Z-wave driver. REALLY need it tested.. pls alert me asap if you find any errors.
https://homey.app/a/com.philio/test/

**Comment by JohanBendz** [comment]
Now live.
