### ISSUE TITLE
SDK3 Beta issue

### ISSUE THREAD

**Issue by Dici71** [Inversion-NL/com.philio#93]
Hi,

we use several Philios PAN08 roller shutters who don't work after update the actual SDK3 beta.

please see the attached picture.....

![PHOTO-2023-01-31-19-08-44](https://user-images.githubusercontent.com/90046346/215848466-cd36b97c-6953-4dcb-8a2a-51e745b3a1d4.jpg)

**Comment by JohanBendz** [comment]
Hi, thanks for the feedback.
Please send a crash report from the app, mark it with your alias/name.

**Comment by JohanBendz** [comment]
@Dici71 Should work now, please get back if something is not working.
