### ISSUE TITLE
PSP05 not reporting

### ISSUE THREAD

**Issue by Gammelgreggan** [Inversion-NL/com.philio#95]
Since upgrade to latest app version my motion sensors PSP05 does not report any motion.

Diagnostic report:
18902c30-43c3-4ac4-85a5-2df4107b010b

**Comment by JohanBendz** [comment]
Hi @Gammelgreggan, please try this one: https://homey.app/a/com.philio/test/

**Comment by Gammelgreggan** [comment]
In test now

Den sön 12 feb. 2023 12:23Johan Bendz ***@***.***> skrev:

**Comment by Gammelgreggan** [comment]
Still no reporting

**Comment by Gammelgreggan** [comment]
f5ab4dda-91b0-4c70-86e1-294ae2b49f6a

**Comment by Gammelgreggan** [comment]
Seems to work, will test some more.

684efab2-7157-4f57-a427-9fe353dac1bb

**Comment by Gammelgreggan** [comment]
Working, thanks for quick fix.

a9734d37-f493-4fe7-8798-b0da842e8fe8
